### ISSUE TITLE
Webpack 5 | Error: Plugin name should be specified

### ISSUE THREAD

**Issue by firestar300** [rpominov/svgo-loader#39]
Hello,

Is SVGO-Loader compatible with Webpack 5?
I got this error when I build my js.

```
ERROR in ./src/img/icons/viadeo.svg
Module build failed (from ./node_modules/svgo-loader/index.js):
Error: Plugin name should be specified
    at resolvePluginConfig (node_modules/svgo/lib/svgo/config.js:98:13)
    at node_modules/svgo/lib/svgo.js:46:7
    at Array.map (<anonymous>)
    at optimize (node_modules/svgo/lib/svgo.js:45:37)
    at Object.loader (node_modules/svgo-loader/index.js:12:18)
 @ ./src/img/icons/ sync \.svg$ ./viadeo.svg
 @ ./src/js/app.js 14:11-58
```

Here my loader configuration : 
```js
test: /icons\/.*\.svg$/,
  use: [
    {
      loader: 'svg-sprite-loader',
      options: {
        extract: true,
        publicPath: 'img/icons/',
        spriteFilename: svgPath => `icons${svgPath.substr(-4)}`,
        symbolId: filePath => `icon-${path.basename(filePath).slice(0, -4)}`,
      },
    },
    {
      loader: 'svgo-loader',
    },
  ],
```

**Comment by firestar300** [comment]
Weird, I don't get this error anymore.

**Comment by MGafitescu** [comment]
@firestar300 Did you do anything specific to get rid of it?
I'm getting the same error,

**Comment by benleilei** [comment]
when you set svgo to 2.3.0, svgo-loader to 3.0.0，svgo-loader config must change
webpack before
```
loader: 'svgo-loader',
options: { 
  plugins: [
    {"cleanupAttrs": true},
    {"cleanupEnableBackground": true}, 
    ... ,
    {
      "removeAttrs": {
        "attrs": ["fill", "fill-rule", "path:fill", "path:class"]
      }
    }
  ]
}
```
webpack after
```
loader: 'svgo-loader',
options: { 
  plugins: [
    {"name": "cleanupAttrs"},
    {"name": "cleanupEnableBackground"}, 
    ... ,
    {
      "name": "removeAttrs",
      "params": {
        "attrs": ["fill", "fill-rule", "path:fill", "path:class"]
      }
    }
  ]
}
```
