### ISSUE TITLE
svgo-loader not working with Webpack 2

### ISSUE THREAD

**Issue by kazazor** [rpominov/svgo-loader#6]
I'm getting this error:
```
Uncaught Error: Module build failed: TypeError: Can't add property config, object is not extensible
    at Object.module.exports (/Users/orkazaz/Developments/Autodesk/BIM360/omri-quality-fork/quality-ui-web/node_modules/svgo/lib/svgo.js:21:17)
    at Object.module.exports (/Users/orkazaz/Developments/Autodesk/BIM360/omri-quality-fork/quality-ui-web/node_modules/svgo/lib/svgo.js:21:17)
    at Object.Accordion.render.__WEBPACK_IMPORTED_MODULE_4_react___default.a.createElement.__WEBPACK_IMPORTED_MODULE_0_babel_runtime_helpers_extends___default.accordion (http://localhost:3001/application-0e88b1e2e0d44eb75e53.js:44667:7)
    at __webpack_require__ (http://localhost:3001/commons-0e88b1e2e0d44eb75e53.js:692:30)
```

In webpack 2 top level configs are not allowed, so this option is NOT good anymore:
```js
module.exports = {
  ...
  module: {
    loaders: [
      {
        test: /.*\.svg$/,
        loaders: [
          'file-loader',
          'svgo-loader?useConfig=svgoConfig1'
        ]
      }
    ]
  },
  svgoConfig1: {
    plugins: [
      {removeTitle: true},
      {convertColors: {shorthex: false}},
      {convertPathData: false}
    ]
  }
}
```

I actually used `svgo-loader` before upgrading to webpack 2.

Some base assumptions for the webpack 2 tries I had:
1. Ignore why I'm using also the `raw-loader` there.. Kind of something to implement an SVG store.
2. `require('./svgo.plugins')` returns us:
```
{
  plugin: [
    { cleanupAttrs: true },
    { removeDoctype: true },
    { removeXMLProcInst: true },
    { removeComments: true },
    { removeMetadata: true },
    { removeTitle: true }, // Changed from default of `false`
    { removeDesc: true },
    { removeUselessDefs: true },
    { removeXMLNS: false },
    { removeEditorsNSData: true },
    { removeEmptyAttrs: true },
    { removeHiddenElems: true },
    { removeEmptyText: true },
    { removeEmptyContainers: true },
    { removeViewBox: false },
    { cleanUpEnableBackground: true },
    { minifyStyles: true },
    { convertStyleToAttrs: true },
    { convertColors: true },
    { convertPathData: true },
    { convertTransform: true },
    { removeUnknownsAndDefaults: true },
    { removeNonInheritableGroupAttrs: true },
    { removeUselessStrokeAndFill: true },
    { removeUnusedNS: true },
    { cleanupIDs: true },
    { cleanupNumericValues: true },
    { cleanupListOfValues: true },
    { moveElemsAttrsToGroup: true },
    { moveGroupAttrsToElems: true },
    { removeRasterImages: false },
    { mergePaths: true },
    { convertShapeToPath: true },
    { sortAttrs: false },
    { transformsWithOnePath: false },
    { removeDimensions: true }, // Changed from default of `false`
    { removeAttrs: false },
    { removeElementsByAttr: false },
    { addClassesToSVGElement: false },
    { addAttributesToSVGElement: false },
    { removeStyleElement: false }
  ]
}
```

And this is how I tried using it now with webpack 2:
```js
      {
        test: /\.svg$/,
        use: [
          {
            loader: 'raw-loader'
          },
          {
            loader: 'svgo?' + JSON.stringify(require('./svgo.plugins'))
          }
        ]
      },
```

Also tried this:
```js
      {
        test: /\.svg$/,
        use: [
          {
            loader: 'raw-loader'
          },
          {
            loader: 'svgo',
            options: require('./svgo.plugins')
          }
        ]
      },
```

Nothing seems to work. Can someone please help out here?

**Comment by rpominov** [comment]
Would be great if someone could look into it and submit a PR! Not sure if I'll be able to do this anytime soon.

**Comment by kazazor** [comment]
Well it seems that it does work and I had an error there.
However, it did show me that a documentation for webpack 2 should be added. I created a pull request to add that + a comment in the code itself about the `useConfig` that will not work on webpack 2

If you can review and approve that it would be great :)

**Comment by rpominov** [comment]
Cool! Closing this issue then.

**Comment by Knovour** [comment]
Try this 
```js
// Add this to your plugins in webpack.config
new webpack.LoaderOptionsPlugin({
  options: {
    svgoConfig: { plugins: [ YOUR_PLUGINS ] }
  }
})
```
then use `svgo-loader?useConfig=svgoConfig` in loaders
